/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as WalletRouteImport } from './routes/wallet'
import { Route as VisaRouteImport } from './routes/visa'
import { Route as VacanciesRouteImport } from './routes/vacancies'
import { Route as TranslatorsRouteImport } from './routes/translators'
import { Route as SkillsRouteImport } from './routes/skills'
import { Route as RewardsRouteImport } from './routes/rewards'
import { Route as ResumeRouteImport } from './routes/resume'
import { Route as MentorRouteImport } from './routes/mentor'
import { Route as JargonRouteImport } from './routes/jargon'
import { Route as InsuranceRouteImport } from './routes/insurance'
import { Route as HousingRouteImport } from './routes/housing'
import { Route as FreelanceRouteImport } from './routes/freelance'
import { Route as ForumRouteImport } from './routes/forum'
import { Route as FamilyRouteImport } from './routes/family'
import { Route as EmployerRouteImport } from './routes/employer'
import { Route as DiplomaRouteImport } from './routes/diploma'
import { Route as CargoRouteImport } from './routes/cargo'
import { Route as CalculatorRouteImport } from './routes/calculator'
import { Route as AuthRouteImport } from './routes/auth'
import { Route as AtsRouteImport } from './routes/ats'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ApiChatRouteImport } from './routes/api/chat'

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport,
} as any)
const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport,
} as any)
const VacanciesRoute = VacanciesRouteImport.update({
  id: '/vacancies',
  path: '/vacancies',
  getParentRoute: () => rootRouteImport,
} as any)
const TranslatorsRoute = TranslatorsRouteImport.update({
  id: '/translators',
  path: '/translators',
  getParentRoute: () => rootRouteImport,
} as any)
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport,
} as any)
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport,
} as any)
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport,
} as any)
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport,
} as any)
const JargonRoute = JargonRouteImport.update({
  id: '/jargon',
  path: '/jargon',
  getParentRoute: () => rootRouteImport,
} as any)
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport,
} as any)
const HousingRoute = HousingRouteImport.update({
  id: '/housing',
  path: '/housing',
  getParentRoute: () => rootRouteImport,
} as any)
const FreelanceRoute = FreelanceRouteImport.update({
  id: '/freelance',
  path: '/freelance',
  getParentRoute: () => rootRouteImport,
} as any)
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport,
} as any)
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport,
} as any)
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport,
} as any)
const DiplomaRoute = DiplomaRouteImport.update({
  id: '/diploma',
  path: '/diploma',
  getParentRoute: () => rootRouteImport,
} as any)
const CargoRoute = CargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => rootRouteImport,
} as any)
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport,
} as any)
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AtsRoute = AtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/ats': typeof AtsRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/cargo': typeof CargoRoute
  '/diploma': typeof DiplomaRoute
  '/employer': typeof EmployerRoute
  '/family': typeof FamilyRoute
  '/forum': typeof ForumRoute
  '/freelance': typeof FreelanceRoute
  '/housing': typeof HousingRoute
  '/insurance': typeof InsuranceRoute
  '/jargon': typeof JargonRoute
  '/mentor': typeof MentorRoute
  '/resume': typeof ResumeRoute
  '/rewards': typeof RewardsRoute
  '/skills': typeof SkillsRoute
  '/translators': typeof TranslatorsRoute
  '/vacancies': typeof VacanciesRoute
  '/visa': typeof VisaRoute
  '/wallet': typeof WalletRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/ats': typeof AtsRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/cargo': typeof CargoRoute
  '/diploma': typeof DiplomaRoute
  '/employer': typeof EmployerRoute
  '/family': typeof FamilyRoute
  '/forum': typeof ForumRoute
  '/freelance': typeof FreelanceRoute
  '/housing': typeof HousingRoute
  '/insurance': typeof InsuranceRoute
  '/jargon': typeof JargonRoute
  '/mentor': typeof MentorRoute
  '/resume': typeof ResumeRoute
  '/rewards': typeof RewardsRoute
  '/skills': typeof SkillsRoute
  '/translators': typeof TranslatorsRoute
  '/vacancies': typeof VacanciesRoute
  '/visa': typeof VisaRoute
  '/wallet': typeof WalletRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/ats': typeof AtsRoute
  '/auth': typeof AuthRoute
  '/calculator': typeof CalculatorRoute
  '/cargo': typeof CargoRoute
  '/diploma': typeof DiplomaRoute
  '/employer': typeof EmployerRoute
  '/family': typeof FamilyRoute
  '/forum': typeof ForumRoute
  '/freelance': typeof FreelanceRoute
  '/housing': typeof HousingRoute
  '/insurance': typeof InsuranceRoute
  '/jargon': typeof JargonRoute
  '/mentor': typeof MentorRoute
  '/resume': typeof ResumeRoute
  '/rewards': typeof RewardsRoute
  '/skills': typeof SkillsRoute
  '/translators': typeof TranslatorsRoute
  '/vacancies': typeof VacanciesRoute
  '/visa': typeof VisaRoute
  '/wallet': typeof WalletRoute
  '/api/chat': typeof ApiChatRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/ats'
    | '/auth'
    | '/calculator'
    | '/cargo'
    | '/diploma'
    | '/employer'
    | '/family'
    | '/forum'
    | '/freelance'
    | '/housing'
    | '/insurance'
    | '/jargon'
    | '/mentor'
    | '/resume'
    | '/rewards'
    | '/skills'
    | '/translators'
    | '/vacancies'
    | '/visa'
    | '/wallet'
    | '/api/chat'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/ats'
    | '/auth'
    | '/calculator'
    | '/cargo'
    | '/diploma'
    | '/employer'
    | '/family'
    | '/forum'
    | '/freelance'
    | '/housing'
    | '/insurance'
    | '/jargon'
    | '/mentor'
    | '/resume'
    | '/rewards'
    | '/skills'
    | '/translators'
    | '/vacancies'
    | '/visa'
    | '/wallet'
    | '/api/chat'
  id:
    | '__root__'
    | '/'
    | '/ats'
    | '/auth'
    | '/calculator'
    | '/cargo'
    | '/diploma'
    | '/employer'
    | '/family'
    | '/forum'
    | '/freelance'
    | '/housing'
    | '/insurance'
    | '/jargon'
    | '/mentor'
    | '/resume'
    | '/rewards'
    | '/skills'
    | '/translators'
    | '/vacancies'
    | '/visa'
    | '/wallet'
    | '/api/chat'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AtsRoute: typeof AtsRoute
  AuthRoute: typeof AuthRoute
  CalculatorRoute: typeof CalculatorRoute
  CargoRoute: typeof CargoRoute
  DiplomaRoute: typeof DiplomaRoute
  EmployerRoute: typeof EmployerRoute
  FamilyRoute: typeof FamilyRoute
  ForumRoute: typeof ForumRoute
  FreelanceRoute: typeof FreelanceRoute
  HousingRoute: typeof HousingRoute
  InsuranceRoute: typeof InsuranceRoute
  JargonRoute: typeof JargonRoute
  MentorRoute: typeof MentorRoute
  ResumeRoute: typeof ResumeRoute
  RewardsRoute: typeof RewardsRoute
  SkillsRoute: typeof SkillsRoute
  TranslatorsRoute: typeof TranslatorsRoute
  VacanciesRoute: typeof VacanciesRoute
  VisaRoute: typeof VisaRoute
  WalletRoute: typeof WalletRoute
  ApiChatRoute: typeof ApiChatRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/wallet': {
      id: '/wallet'
      path: '/wallet'
      fullPath: '/wallet'
      preLoaderRoute: typeof WalletRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/visa': {
      id: '/visa'
      path: '/visa'
      fullPath: '/visa'
      preLoaderRoute: typeof VisaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/vacancies': {
      id: '/vacancies'
      path: '/vacancies'
      fullPath: '/vacancies'
      preLoaderRoute: typeof VacanciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/translators': {
      id: '/translators'
      path: '/translators'
      fullPath: '/translators'
      preLoaderRoute: typeof TranslatorsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/skills': {
      id: '/skills'
      path: '/skills'
      fullPath: '/skills'
      preLoaderRoute: typeof SkillsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/rewards': {
      id: '/rewards'
      path: '/rewards'
      fullPath: '/rewards'
      preLoaderRoute: typeof RewardsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/resume': {
      id: '/resume'
      path: '/resume'
      fullPath: '/resume'
      preLoaderRoute: typeof ResumeRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mentor': {
      id: '/mentor'
      path: '/mentor'
      fullPath: '/mentor'
      preLoaderRoute: typeof MentorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/jargon': {
      id: '/jargon'
      path: '/jargon'
      fullPath: '/jargon'
      preLoaderRoute: typeof JargonRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/insurance': {
      id: '/insurance'
      path: '/insurance'
      fullPath: '/insurance'
      preLoaderRoute: typeof InsuranceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/housing': {
      id: '/housing'
      path: '/housing'
      fullPath: '/housing'
      preLoaderRoute: typeof HousingRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/freelance': {
      id: '/freelance'
      path: '/freelance'
      fullPath: '/freelance'
      preLoaderRoute: typeof FreelanceRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/forum': {
      id: '/forum'
      path: '/forum'
      fullPath: '/forum'
      preLoaderRoute: typeof ForumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/family': {
      id: '/family'
      path: '/family'
      fullPath: '/family'
      preLoaderRoute: typeof FamilyRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/employer': {
      id: '/employer'
      path: '/employer'
      fullPath: '/employer'
      preLoaderRoute: typeof EmployerRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/diploma': {
      id: '/diploma'
      path: '/diploma'
      fullPath: '/diploma'
      preLoaderRoute: typeof DiplomaRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/cargo': {
      id: '/cargo'
      path: '/cargo'
      fullPath: '/cargo'
      preLoaderRoute: typeof CargoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/calculator': {
      id: '/calculator'
      path: '/calculator'
      fullPath: '/calculator'
      preLoaderRoute: typeof CalculatorRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/auth': {
      id: '/auth'
      path: '/auth'
      fullPath: '/auth'
      preLoaderRoute: typeof AuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ats': {
      id: '/ats'
      path: '/ats'
      fullPath: '/ats'
      preLoaderRoute: typeof AtsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/api/chat': {
      id: '/api/chat'
      path: '/api/chat'
      fullPath: '/api/chat'
      preLoaderRoute: typeof ApiChatRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AtsRoute: AtsRoute,
  AuthRoute: AuthRoute,
  CalculatorRoute: CalculatorRoute,
  CargoRoute: CargoRoute,
  DiplomaRoute: DiplomaRoute,
  EmployerRoute: EmployerRoute,
  FamilyRoute: FamilyRoute,
  ForumRoute: ForumRoute,
  FreelanceRoute: FreelanceRoute,
  HousingRoute: HousingRoute,
  InsuranceRoute: InsuranceRoute,
  JargonRoute: JargonRoute,
  MentorRoute: MentorRoute,
  ResumeRoute: ResumeRoute,
  RewardsRoute: RewardsRoute,
  SkillsRoute: SkillsRoute,
  TranslatorsRoute: TranslatorsRoute,
  VacanciesRoute: VacanciesRoute,
  VisaRoute: VisaRoute,
  WalletRoute: WalletRoute,
  ApiChatRoute: ApiChatRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.jsx'
import type { startInstance } from './start.js'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
