/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root';
import { Route as WalletRouteImport } from './routes/wallet';
import { Route as VisaRouteImport } from './routes/visa';
import { Route as VacanciesRouteImport } from './routes/vacancies';
import { Route as TranslatorsRouteImport } from './routes/translators';
import { Route as SkillsRouteImport } from './routes/skills';
import { Route as RewardsRouteImport } from './routes/rewards';
import { Route as ResumeRouteImport } from './routes/resume';
import { Route as MentorRouteImport } from './routes/mentor';
import { Route as JargonRouteImport } from './routes/jargon';
import { Route as InsuranceRouteImport } from './routes/insurance';
import { Route as HousingRouteImport } from './routes/housing';
import { Route as FreelanceRouteImport } from './routes/freelance';
import { Route as ForumRouteImport } from './routes/forum';
import { Route as FamilyRouteImport } from './routes/family';
import { Route as EmployerRouteImport } from './routes/employer';
import { Route as DiplomaRouteImport } from './routes/diploma';
import { Route as CargoRouteImport } from './routes/cargo';
import { Route as CalculatorRouteImport } from './routes/calculator';
import { Route as AuthRouteImport } from './routes/auth';
import { Route as AtsRouteImport } from './routes/ats';
import { Route as IndexRouteImport } from './routes/index';
import { Route as ApiChatRouteImport } from './routes/api/chat';

const WalletRoute = WalletRouteImport.update({
  id: '/wallet',
  path: '/wallet',
  getParentRoute: () => rootRouteImport
});
const VisaRoute = VisaRouteImport.update({
  id: '/visa',
  path: '/visa',
  getParentRoute: () => rootRouteImport
});
const VacanciesRoute = VacanciesRouteImport.update({
  id: '/vacancies',
  path: '/vacancies',
  getParentRoute: () => rootRouteImport
});
const TranslatorsRoute = TranslatorsRouteImport.update({
  id: '/translators',
  path: '/translators',
  getParentRoute: () => rootRouteImport
});
const SkillsRoute = SkillsRouteImport.update({
  id: '/skills',
  path: '/skills',
  getParentRoute: () => rootRouteImport
});
const RewardsRoute = RewardsRouteImport.update({
  id: '/rewards',
  path: '/rewards',
  getParentRoute: () => rootRouteImport
});
const ResumeRoute = ResumeRouteImport.update({
  id: '/resume',
  path: '/resume',
  getParentRoute: () => rootRouteImport
});
const MentorRoute = MentorRouteImport.update({
  id: '/mentor',
  path: '/mentor',
  getParentRoute: () => rootRouteImport
});
const JargonRoute = JargonRouteImport.update({
  id: '/jargon',
  path: '/jargon',
  getParentRoute: () => rootRouteImport
});
const InsuranceRoute = InsuranceRouteImport.update({
  id: '/insurance',
  path: '/insurance',
  getParentRoute: () => rootRouteImport
});
const HousingRoute = HousingRouteImport.update({
  id: '/housing',
  path: '/housing',
  getParentRoute: () => rootRouteImport
});
const FreelanceRoute = FreelanceRouteImport.update({
  id: '/freelance',
  path: '/freelance',
  getParentRoute: () => rootRouteImport
});
const ForumRoute = ForumRouteImport.update({
  id: '/forum',
  path: '/forum',
  getParentRoute: () => rootRouteImport
});
const FamilyRoute = FamilyRouteImport.update({
  id: '/family',
  path: '/family',
  getParentRoute: () => rootRouteImport
});
const EmployerRoute = EmployerRouteImport.update({
  id: '/employer',
  path: '/employer',
  getParentRoute: () => rootRouteImport
});
const DiplomaRoute = DiplomaRouteImport.update({
  id: '/diploma',
  path: '/diploma',
  getParentRoute: () => rootRouteImport
});
const CargoRoute = CargoRouteImport.update({
  id: '/cargo',
  path: '/cargo',
  getParentRoute: () => rootRouteImport
});
const CalculatorRoute = CalculatorRouteImport.update({
  id: '/calculator',
  path: '/calculator',
  getParentRoute: () => rootRouteImport
});
const AuthRoute = AuthRouteImport.update({
  id: '/auth',
  path: '/auth',
  getParentRoute: () => rootRouteImport
});
const AtsRoute = AtsRouteImport.update({
  id: '/ats',
  path: '/ats',
  getParentRoute: () => rootRouteImport
});
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport
});
const ApiChatRoute = ApiChatRouteImport.update({
  id: '/api/chat',
  path: '/api/chat',
  getParentRoute: () => rootRouteImport
});

const rootRouteChildren = {
  IndexRoute: IndexRoute,
  AtsRoute: AtsRoute,
  AuthRoute: AuthRoute,
  CalculatorRoute: CalculatorRoute,
  CargoRoute: CargoRoute,
  DiplomaRoute: DiplomaRoute,
  EmployerRoute: EmployerRoute,
  FamilyRoute: FamilyRoute,
  ForumRoute: ForumRoute,
  FreelanceRoute: FreelanceRoute,
  HousingRoute: HousingRoute,
  InsuranceRoute: InsuranceRoute,
  JargonRoute: JargonRoute,
  MentorRoute: MentorRoute,
  ResumeRoute: ResumeRoute,
  RewardsRoute: RewardsRoute,
  SkillsRoute: SkillsRoute,
  TranslatorsRoute: TranslatorsRoute,
  VacanciesRoute: VacanciesRoute,
  VisaRoute: VisaRoute,
  WalletRoute: WalletRoute,
  ApiChatRoute: ApiChatRoute
};

export const routeTree = rootRouteImport._addFileChildren(rootRouteChildren);